/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package OHOS.AppExecFwk;
interface_token ohos.bundleManager.OverlayManager;
sequenceable Overlay.OverlayBundleInfo..OHOS.AppExecFwk.OverlayBundleInfo;
sequenceable Overlay.OverlayModuleInfo..OHOS.AppExecFwk.OverlayModuleInfo;
option_stub_hooks on;
 interface OHOS.AppExecFwk.IOverlayManager {
    [ipccode 0] void GetAllOverlayModuleInfo([in] String bundleName, [in] int userId, [out] OverlayModuleInfo[] overlayModuleInfos,
        [out] int funcResult);
    [ipccode 1] void GetOverlayModuleInfo([in] String bundleName, [in] String moduleName, [in] int userId,
        [out] OverlayModuleInfo overlayModuleInfo, [out] int funcResult);
    [ipccode 2] void GetOverlayModuleInfo([in] String moduleName, [in] int userId,
        [out] OverlayModuleInfo overlayModuleInfo, [out] int funcResult);
    [ipccode 3] void GetTargetOverlayModuleInfo([in] String targetModuleName, [in] int userId,
        [out] OverlayModuleInfo[] overlayModuleInfos, [out] int funcResult);
    [ipccode 4] void GetOverlayModuleInfoByBundleName([in] String bundleName, [in] String moduleName, [in] int userId,
        [out] OverlayModuleInfo[] overlayModuleInfos, [out] int funcResult);
    [ipccode 5] void GetOverlayBundleInfoForTarget([in] String targetBundleName, [in] int userId,
        [out] OverlayBundleInfo[] overlayBundleInfos, [out] int funcResult);
    [ipccode 6] void GetOverlayModuleInfoForTarget([in] String targetBundleName, [in] String targetModuleName,
        [in] int userId,[out] OverlayModuleInfo[] overlayModuleInfos, [out] int funcResult);
    [ipccode 7] void SetOverlayEnabled([in] String bundleName, [in] String moduleName, [in] boolean isEnabled,
        [in] int userId, [out] int funcResult);
    [ipccode 8] void SetOverlayEnabledForSelf([in] String moduleName, [in] boolean isEnabled, [in] int userId,
        [out] int funcResult);
 }