/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef FOUNDATION_APPEXECFWK_SERVICES_BUNDLEMGR_INCLUDE_INSTALLD_CONSTANTS_H
#define FOUNDATION_APPEXECFWK_SERVICES_BUNDLEMGR_INCLUDE_INSTALLD_CONSTANTS_H

#include "appexecfwk_errors.h"

namespace OHOS {
namespace AppExecFwk {
enum class ScanMode : uint8_t {
    SUB_FILE_ALL = 0,
    SUB_FILE_DIR,
    SUB_FILE_FILE,
};

enum class ResultMode : uint8_t {
    ABSOLUTE_PATH = 0,
    RELATIVE_PATH,
};

enum class BundleDirScene : int32_t {
    SET_DIR_APL = 0,
    EXTRACT_HNP_FILES = 1,
    SET_FILE_CON_FORCE = 2,
    EXTRACT_DRIVER_SO_FILES = 3,
    SET_ARK_STARTUP_CACHE_APL = 4,
    PEND_SIGN_AOT = 5,
    EXTRACT_FILES = 6,
    VERIFY_CODE_SIGNATURE = 7,
    REMOVE_EXTENSION_DIR = 8,
    CLEAN_BUNDLE_DATA_DIR = 9,

    // CreateBundleDir scenes
    BUNDLE_CODE_DIR = 101,
    MODULE_DIR = 102,
    SO_DIR = 103,
    EXTEND_RESOURCE_DIR = 104,
    EXTEND_PROFILE_DIR = 105,
    PLUGIN_DIR = 106,
    QUICKFIX_PATCH_DIR = 107,
    VERIFY_DIR = 108,
    BASE_SKILL_DIR = 109,

    // Mkdir scenes
    EL1_ARK_PROFILE_DIR = 201,
    ASAN_LOG_DIR = 202,
    EL1_ARK_STARTUP_CACHE_DIR = 203,
    SHADER_CACHE_DIR = 204,
    CLOUD_SHADER_DIR = 205,
    CLOUD_SHADER_COMMON_DIR = 206,
    SERVICE_BMS_GALLERY_DOWNLOAD_DIR = 207,
    SCREEN_LOCK_FILE_BASE_DIR = 208,
    SCREEN_LOCK_FILE_DATA_BASE_DIR = 209,
    SERVICE_BMS_ENTERPRISE_CERT_DIR = 210,
    EL1_SHADER_CACHE_DIR = 211,
    EL1_SYSTEM_OPTIMIZE_SHADER_CACHE_DIR = 212,
    EL1_SYSTEM_OPTIMIZE_DIR = 213,
    SERVICE_BMS_DIR = 214,
    SERVICE_BMS_SECURITY_STREAM_INSTALL_DIR = 215,
    SCREEN_LOCK_FILE_DATA_GROUP_DIR = 216,
    BACK_UP_DIR = 217,
    APP_EL2_LOG_DIR = 218,
    SERVICE_HMDFS_CLOUD_DATA_DIR = 219,
    EL2_SHARE_FILES_DIR = 220,
    PGO_DIR = 221,

    // MoveFile scenes
    MOVE_HAP_TO_INSTALL_DIR = 301,
    MOVE_HAP_TO_TEMP_DIR = 302,
    MOVE_DRIVER_FILE = 303,
    MOVE_EXTEND_RESOURCE_FILE = 304,
    MOVE_EXTEND_RESOURCE_FILE_TO_TEMP_DIR = 305,
    MOVE_HSP_TO_INSTALL_DIR = 306,
    MOVE_ABC_FILE = 307,
};

const std::unordered_map<int32_t, int32_t> CODE_SIGNATURE_ERR_MAP = {
    {1, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_CS_SUCCESS_END},
    {-0x101, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_FILE_PATH_INVALID},
    {-0x200, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_PARAM_INVALID},
    {-0x205, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_NO_OWNER_ID},
    {-0x214, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_OPENSSL_BIO},
    {-0x212, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_OPENSSL_PKCS7},
    {-0x301, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_FSVREITY_NOT_SUPPORTED},
    {-0x302, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_FSVERITY_NOT_ENABLED},
    {-0x303, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_INVALID_OWNER_ID},
    {-0x305, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_ERR_PROFILE},
    {-0x306, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_ENABLE_TIMEOUT},
    {-0x622, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_INVALID_EXTENSION_OFFSET},
    {-0x623, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_INVALID_PAGE_INFO_EXTENSION},
    {-0x624, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_EXTENSION_SIGN_SIZE},

};
}  // namespace AppExecFwk
}  // namespace OHOS
#endif  // FOUNDATION_APPEXECFWK_SERVICES_BUNDLEMGR_INCLUDE_INSTALLD_CONSTANTS_H
