/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef FOUNDATION_APPEXECFWK_SERVICES_BUNDLEMGR_INCLUDE_INSTALLD_CONSTANTS_H
#define FOUNDATION_APPEXECFWK_SERVICES_BUNDLEMGR_INCLUDE_INSTALLD_CONSTANTS_H

namespace OHOS {
namespace AppExecFwk {
enum class ScanMode : uint8_t {
    SUB_FILE_ALL = 0,
    SUB_FILE_DIR,
    SUB_FILE_FILE,
};

enum class ResultMode : uint8_t {
    ABSOLUTE_PATH = 0,
    RELATIVE_PATH,
};

const std::unordered_map<int32_t, int32_t> CODE_SIGNATURE_ERR_MAP = {
    {1, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_CS_SUCCESS_END},
    {-0x101, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_FILE_PATH_INVALID},
    {-0x200, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_PARAM_INVALID},
    {-0x205, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_NO_OWNER_ID},
    {-0x214, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_OPENSSL_BIO},
    {-0x212, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_OPENSSL_PKCS7},
    {-0x301, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_FSVREITY_NOT_SUPPORTED},
    {-0x302, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_FSVERITY_NOT_ENABLED},
    {-0x303, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_INVALID_OWNER_ID},
    {-0x306, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_ENABLE_TIMEOUT},
    {-0x622, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_INVALID_EXTENSION_OFFSET},
    {-0x623, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_INVALID_PAGE_INFO_EXTENSION},
    {-0x624, ERR_BUNDLEMANAGER_INSTALL_CODE_SIGNATURE_EXTENSION_SIGN_SIZE},
};
}  // namespace AppExecFwk
}  // namespace OHOS
#endif  // FOUNDATION_APPEXECFWK_SERVICES_BUNDLEMGR_INCLUDE_INSTALLD_CONSTANTS_H
